### PR TITLE
Create home sections - search bar, filters, cards

### PR DESCRIPTION
**Pull request by aelaser**

### CODE REVIEW

**Review by EnocFlores — DISMISSED** [review]
Looks good

**Comment by Abner3** [comment]
We should really consider merging with master at this point. Still need to implement date filter, but aside from that I don't think there's anything else. We also need to decide whether posts show up before a user searches or posts don't show up before a search. @aelaser @EnocFlores

**Review by Schm2000 — APPROVED** [review]
I agree with Abner, we can carry over the changes we still have to implement over to different branches.

**Review by EnocFlores — APPROVED** [review]
Sprint 6 is good to merge

**Pull request merged**
